### ISSUE TITLE
Clang Format style

### ISSUE THREAD

**Issue by andreas-bauer** [PerssonAlbin/file-editor_OWN_CPP#39]
Clang-Format should be used to maintain a constant code style. 

The following base styles are supported by Clang-Format: LLVM, GNU, Google, Chromium, Microsoft, Mozilla, WebKit.

LLVM seems to be the default fallback style.

You can use the [clang-format-configurator](https://zed0.co.uk/clang-format-configurator/) and pick the style that you prefer the most.

**Comment by PerssonAlbin** [comment]
Was fixed with PR #43
